# Generated by Django 2.1.2 on 2018-11-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auctions', '0005_item_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
