# Generated by Django 2.1.3 on 2018-11-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auctions', '0009_auto_20181116_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_pic',
            field=models.ImageField(default='no_image.png', upload_to='item_pics'),
        ),
    ]
