# Generated by Django 2.1.2 on 2018-12-12 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auctions', '0011_auto_20181118_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('Item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Auctions.Item')),
            ],
        ),
    ]
