# Generated by Django 2.1.2 on 2018-11-19 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0004_auto_20181116_2332'),
        ('Auctions', '0011_auto_20181118_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentHighestBid', models.IntegerField(default=0)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auctions.Auction')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoldItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WinningBid', models.IntegerField(default=0)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Profile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auctions.Item')),
            ],
        ),
    ]
