# Generated by Django 2.1.2 on 2018-11-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAuctionPortal', '0002_auto_20181124_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='current_item_base_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='current_item_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='test',
            name='current_item_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='test',
            name='nextbhejukya',
            field=models.BooleanField(default=False),
        ),
    ]
