# Generated by Django 2.1.2 on 2018-11-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAuctionPortal', '0003_auto_20181125_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='current_item_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='no_of_items',
            field=models.IntegerField(default=0),
        ),
    ]
