# Generated by Django 2.1.2 on 2018-11-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestAuctionPortal', '0004_auto_20181125_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='userprofile',
        ),
    ]
