# Generated by Django 2.1.2 on 2018-12-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestAuctionPortal', '0005_remove_test_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='current_item_base_price',
        ),
        migrations.RemoveField(
            model_name='test',
            name='current_item_description',
        ),
        migrations.RemoveField(
            model_name='test',
            name='current_item_name',
        ),
        migrations.RemoveField(
            model_name='test',
            name='current_item_no',
        ),
        migrations.RemoveField(
            model_name='test',
            name='nextbhejukya',
        ),
        migrations.RemoveField(
            model_name='test',
            name='no_of_items',
        ),
    ]
