# Generated by Django 2.1.2 on 2018-12-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAuctionPortal', '0007_test_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='auctionid',
            field=models.IntegerField(default=0),
        ),
    ]
