# Generated by Django 2.1.2 on 2018-12-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAuctionPortal', '0009_auto_20181208_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='currentbid',
            new_name='current_bid',
        ),
        migrations.AddField(
            model_name='test',
            name='current_item_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='time_reset',
            field=models.BooleanField(default=False),
        ),
    ]
