# Generated by Django 2.1.2 on 2018-12-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAuctionPortal', '0010_auto_20181208_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='bid_increment',
            field=models.IntegerField(default=0),
        ),
    ]
