# Generated by Django 2.1.2 on 2018-12-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAuctionPortal', '0011_test_bid_increment'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='next_item',
            field=models.BooleanField(default=False),
        ),
    ]
