# Generated by Django 2.1.2 on 2018-12-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20181116_2332'),
        ('Auctions', '0011_auto_20181118_1644'),
        ('RestAuctionPortal', '0013_auto_20181211_2113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SoldItems',
            new_name='SoldItemsData',
        ),
        migrations.RemoveField(
            model_name='currentbid',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='currentbid',
            name='userprofile',
        ),
        migrations.DeleteModel(
            name='CurrentBid',
        ),
    ]
