# Generated by Django 2.1.2 on 2018-12-11 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestAuctionPortal', '0014_auto_20181211_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='next_item',
        ),
    ]
