# Generated by Django 2.1.2 on 2018-12-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestAuctionPortal', '0016_solditemsdata_auction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solditemsdata',
            old_name='auction_id',
            new_name='auction',
        ),
    ]
