# Generated by Django 2.1.3 on 2018-11-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20181111_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_pic',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
